name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install NPM dependencies    
      run: npm install
    - name: Start the application
      run: npm run start &
    - name: Run the Unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "annanatova"